name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots.

