name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: npx prisma generate
      - run: env $(cat .env.ci | xargs) pnpm lint
      - run: env $(cat .env.ci | xargs) pnpm typecheck
      - run: env $(cat .env.ci | xargs) pnpm test
      - run: env $(cat .env.ci | xargs) pnpm exec playwright install --with-deps chromium
      - run: env $(cat .env.ci | xargs) pnpm e2e --browser=chromium
